terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 2.65"
    }
  }

  required_version = ">= 1.1.0"
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg1" {
  name     = "fantasy-nba"
  location = "westeurope"
}

resource "azurerm_storage_account" "nbastorageacc1" {
  name                     = "fantasynba"
  resource_group_name      = azurerm_resource_group.rg1.name
  location                 = azurerm_resource_group.rg1.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_container" "gamesplayedstoragecontainer1" {
  name                  = "gamesplayed"
  storage_account_name  = azurerm_storage_account.nbastorageacc1.name
  container_access_type = "private"
}

resource "azurerm_storage_container" "playerstatsstoragecontainer1" {
  name                  = "playerstats"
  storage_account_name  = azurerm_storage_account.nbastorageacc1.name
  container_access_type = "private"
}

resource "azurerm_storage_queue" "nbastoragestoragequeue1" {
  name                 = "nbastoragequeue"
  storage_account_name = azurerm_storage_account.nbastorageacc1.name
}

resource "azurerm_eventgrid_event_subscription" "nbastoragesubscription1" {
  name  = "nbastoragesubscription"
  scope = azurerm_storage_account.nbastorageacc1.id 

  storage_queue_endpoint {
    storage_account_id = azurerm_storage_account.nbastorageacc1.id
    queue_name         = azurerm_storage_queue.nbastoragestoragequeue1.name
  }
}

resource "azurerm_role_assignment" "snowflakerolestorageaccount" {
  scope                =  azurerm_storage_account.nbastorageacc1.id
  role_definition_name = "Storage Blob Data Contributor"
  principal_id         = "0d6e0089-4fc2-4099-9f20-c5c419d01a6d" # Principal is generated by Snowflake
}

resource "azurerm_role_assignment" "snowflakerolestoragequeue" {
  scope                =  azurerm_storage_account.nbastorageacc1.id
  role_definition_name = "Storage Queue Data Contributor"
  principal_id         = "387a68be-33de-4d2d-9ed8-65e6b4d9fb49" # Principal is generated by Snowflake
}
